FROM rust:1.92.0 AS builder
WORKDIR /app

COPY ./Cargo.* ./

RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release

RUN rm -f src/main.rs
COPY ./src ./src
RUN cargo build --release



FROM debian:bookworm-slim AS runner
WORKDIR /app

COPY --from=builder /app/target/release/tcpchat-server /app
RUN ls -l /app

ENTRYPOINT ["/app/tcpchat-server"]
