FROM golang:latest AS builder
WORKDIR /app

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o tcpchat-client main.go


FROM alpine:latest AS runner
WORKDIR /app

COPY --from=builder /app/tcpchat-client ./

ENTRYPOINT ["/app/tcpchat-client"]
